### ISSUE TITLE
Game crashes when blocking guardian beam with reflection enchanted netherite shield

### ISSUE THREAD

**Issue by HiGuysItsMeSussyBaka** [StellarWind22/Basic-Shields-Fabric#50]
The title says it. When a guardian beam is blocked with a shield that is enchanted with reflection, the game crashes. [crash-2022-10-13_09.03.49-server.txt](https://github.com/CrimsonDawn45/Basic-Shields-Fabric/files/9776921/crash-2022-10-13_09.03.49-server.txt)

**Comment by Zarepheth** [comment]
I suffered similar problem, but the shield was Moissanite (via integration with More Gems). My shield is also enchanted with Reflection and I was also hit by a Guardian's beam when the game crashed.
[crash-2022-11-12_22.29.36-server.txt](https://github.com/CrimsonDawn45/Basic-Shields-Fabric/files/9996514/crash-2022-11-12_22.29.36-server.txt)

**Comment by StellarWind22** [comment]
This issue has been patched in newer versions I just need to backport the fix
