### ISSUE TITLE
Continued Development - 1.20+

### ISSUE THREAD

**Issue by BeardedThorgi** [StellarWind22/Basic-Shields-Fabric#54]
Hello! It seems like development of this mod has stopped, but just wanted to request an update to 1.20+ if that's not the case. If there's no plan to continue working on this mod, feel free to close my issue. Thanks!

**Comment by allanonmage** [comment]
I have this question too.  I guess the good news is that they just recently updated the library this mod depends on, so maybe this is next?

**Comment by StellarWind22** [comment]
I plan on continuing development of this mod. I just haven't had access to a computer capable of programming until recently.
